without cinmonitor execution

diff --git a/.github/workflows/modified.yaml b/.github/workflows/modified.yaml
--- a/.github/workflows/modified.yaml
+++ b/.github/workflows/modified.yaml
@@ -3,14 +3,15 @@
 
 name: BciPy
 
-on:
-  workflow_dispatch: 
-  push:
-    branches:
-      - main
-  pull_request:
-    branches:
-      - '**'
+# CINTENT >> MANUAL_TRIGGER
+# on:
+#   push:
+#     branches:
+#       - main
+#   pull_request:
+#     branches:
+#       - '**'
+on: [repository_dispatch, workflow_dispatch]
 
 jobs:
   build-ubuntu:
@@ -19,14 +20,23 @@ jobs:
     strategy:
       fail-fast: false
       matrix:
-        python-version: [3.9, 3.10.6]
+        # CINTENT >> REMOVE_MATRIX
+        # python-version: [3.9, 3.10.6]
+        python-version: [3.10.6]
 
     steps:
-    - uses: actions/checkout@v2
+    - uses: actions/checkout@v4
+
     - name: Set up Python ${{ matrix.python-version }}
       uses: actions/setup-python@v2
       with:
         python-version: ${{ matrix.python-version }}
+        
+    # # CINTENT >> INSERT_CINTENT
+    # - uses: JavidDitty/setup-cintent@main
+    #   with:
+    #     profiler: "setprofile"
+
     - name: Update OS, pip & install custom dependencies
       run: |
         sudo apt-get update
@@ -39,15 +49,17 @@ jobs:
         python -m pip install --upgrade pip
         pip install attrdict3
         conda install -c conda-forge liblsl
+
     - name: Install dependencies
       run: |
         make dev-install
+
     - name: Unit test
       if: always()
       run: |
         set +e
         xvfb-run coverage run --branch --source=bcipy -m pytest --mpl -k "not slow"
-        if [ $? -eq 0 ]
+        if [ $? -eq 0 ]b
         then 
           echo "Ubuntu run complete!"
         elif [ $? -eq 134 ]
@@ -57,83 +69,95 @@ jobs:
         else 
           echo "Ubuntu test failure"
         fi
+
     - name: type-check
       run: |
         make type
+
     - name: lint
       run: |
         make lint
+        
+    # CINTENT >> INSERT_CINTENT
+    # - name: Upload CIntent Artifacts
+    #   uses: actions/upload-artifact@v4
+    #   if: always()
+    #   with:
+    #     name: ${{ env.CINTENT_ARTIFACT_NAME }}
+    #     path: ${{ env.CINTENT_LOGS }}
 
-  build-windows:
+  # CINTENT >> UNSUPPORTED_OS
+  # build-windows:
 
-    runs-on: windows-latest
-    strategy:
-      fail-fast: false
-      matrix:
-        python-version: [3.9, 3.10.6]
+  #   runs-on: windows-latest
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       python-version: [3.9, 3.10.6]
 
-    steps:
-    - uses: actions/checkout@v2
-    - name: Set up Python ${{ matrix.python-version }}
-      uses: actions/setup-python@v2
-      with:
-        python-version: ${{ matrix.python-version }}
-    - name: update pip & install custom dependencies
-      run: |
-        python -m pip install --upgrade pip
-    - name: install dependencies
-      run: |
-        make dev-install
-    - name: unittest
-      if: always()
-      run: |
-        make coverage-report
-    - name: type-check
-      run: |
-        make type
-    - name: lint
-      run: |
-        make lint
-    - name: build
-      run: |
-        make build
+  #   steps:
+  #   - uses: actions/checkout@v2
+  #   - name: Set up Python ${{ matrix.python-version }}
+  #     uses: actions/setup-python@v2
+  #     with:
+  #       python-version: ${{ matrix.python-version }}
+  #   - name: update pip & install custom dependencies
+  #     run: |
+  #       python -m pip install --upgrade pip
+  #   - name: install dependencies
+  #     run: |
+  #       make dev-install
+  #   - name: unittest
+  #     if: always()
+  #     run: |
+  #       make coverage-report
+  #   - name: type-check
+  #     run: |
+  #       make type
+  #   - name: lint
+  #     run: |
+  #       make lint
+  #   - name: build
+  #     run: |
+  #       make build
 
-  build-macos:
+  # CINTENT >> UNSUPPORTED_OS
+  # build-macos:
 
-    runs-on: macos-14
-    strategy:
-      fail-fast: false
-      matrix:
-        python-version: [3.9, 3.10.6]
+  #   runs-on: macos-14
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       python-version: [3.9, 3.10.6]
 
-    steps:
-    - uses: actions/checkout@v4
-    - name: Set up Python ${{ matrix.python-version }}
-      uses: actions/setup-python@v2
-      with:
-        python-version: ${{ matrix.python-version }}
-    - name: update pip & install custom dependencies
-      run: |
-        python -m pip install --upgrade pip
-        brew update
-        brew uninstall cmake
-        sh scripts/shell/m2chip_install.sh
-        brew install labstreaminglayer/tap/lsl
-        make install
-    - name: install dependencies
-      run: |
-        make dev-install
-    - name: unittest
-      if: always()
-      run: |
-        make coverage-report
-        make coverage-xml
-    - name: type-check
-      run: |
-        make type
-    - name: lint
-      run: |
-        make lint
-    - name: build
-      run: |
-        make build
+  #   steps:
+  #   - uses: actions/checkout@v4
+  #   - name: Set up Python ${{ matrix.python-version }}
+  #     uses: actions/setup-python@v2
+  #     with:
+  #       python-version: ${{ matrix.python-version }}
+  #   - name: update pip & install custom dependencies
+  #     run: |
+  #       python -m pip install --upgrade pip
+  #       brew update
+  #       brew uninstall cmake
+  #       sh scripts/shell/m2chip_install.sh
+  #       brew install labstreaminglayer/tap/lsl
+  #       make install
+  #   - name: install dependencies
+  #     run: |
+  #       make dev-install
+  #   - name: unittest
+  #     if: always()
+  #     run: |
+  #       make coverage-report
+  #       make coverage-xml
+  #   - name: type-check
+  #     run: |
+  #       make type
+  #   - name: lint
+  #     run: |
+  #       make lint
+  #   - name: build
+  #     run: |
+  #       make build
