Update BciPy_Dynapyt_test workflow configuration
Renamed workflow and updated steps for dependency installation and testing.

diff --git a/.github/workflows/test_dynapyt.yaml b/.github/workflows/test_dynapyt.yaml
--- a/.github/workflows/test_dynapyt.yaml
+++ b/.github/workflows/test_dynapyt.yaml
@@ -1,7 +1,7 @@
 # This workflow will install Python dependencies, run tests and lint with a variety of Python versions
 # For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions
 
-name: BciPy_Dynapyt_test
+name: BciPy-MLCIMonitor
 
 # CINTENT >> MANUAL_TRIGGER
 # on:
@@ -32,25 +32,132 @@ jobs:
       with:
         python-version: ${{ matrix.python-version }}
         
-    - name: Start DynaPyt for pip
-      uses: clonedSemicolon/seytup-dynapyt@master
+    # CINTENT >> INSERT_CINTENT
+    - uses: JavidDitty/setup-cintent@main
       with:
-        package: pip
-        analysis: dynapyt.analyses.CallGraph.CallGraph
-        dynapyt_path: git+https://github.com/sola-st/DynaPyt.git@07680e074c9f280c320f9e359500f672b662de7f
-
+        profiler: "setprofile"
 
     - name: Update OS, pip & install custom dependencies
       run: |
         sudo apt-get update
         sudo apt-get install libgtk-3-dev
+        sudo apt-get install freeglut3-dev
+        sudo apt-get install freetype*
+        sudo apt-get install portaudio*
+        sudo apt-get install libsndfile*
+        sudo apt-get install xvfb
+        python -m pip install --upgrade pip
         pip install attrdict3
-    
-    - name: Collect dependency-install trace
-      if: always()
-      uses: clonedSemicolon/seytup-dynapyt@master
-      with:
-        mode: collect
-        artifact-name: dynapyt-install-dependencies
+        conda install -c conda-forge liblsl
 
-    
+    - name: Install dependencies
+      run: |
+        make dev-install
+
+    - name: Unit test
+      if: always()
+      run: |
+        set +e
+        xvfb-run coverage run --branch --source=bcipy -m pytest --mpl -k "not slow"
+        if [ $? -eq 0 ]b
+        then 
+          echo "Ubuntu run complete!"
+        elif [ $? -eq 134 ]
+        then
+          echo "Ubuntu tests run successfully, memory issues may be present"
+          exit 0
+        else 
+          echo "Ubuntu test failure"
+        fi
+
+    - name: type-check
+      run: |
+        make type
+
+    - name: lint
+      run: |
+        make lint
+        
+    # CINTENT >> INSERT_CINTENT
+    - name: Upload CIntent Artifacts
+      uses: actions/upload-artifact@v4
+      if: always()
+      with:
+        name: ${{ env.CINTENT_ARTIFACT_NAME }}
+        path: ${{ env.CINTENT_LOGS }}
+
+  # CINTENT >> UNSUPPORTED_OS
+  # build-windows:
+
+  #   runs-on: windows-latest
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       python-version: [3.9, 3.10.6]
+
+  #   steps:
+  #   - uses: actions/checkout@v2
+  #   - name: Set up Python ${{ matrix.python-version }}
+  #     uses: actions/setup-python@v2
+  #     with:
+  #       python-version: ${{ matrix.python-version }}
+  #   - name: update pip & install custom dependencies
+  #     run: |
+  #       python -m pip install --upgrade pip
+  #   - name: install dependencies
+  #     run: |
+  #       make dev-install
+  #   - name: unittest
+  #     if: always()
+  #     run: |
+  #       make coverage-report
+  #   - name: type-check
+  #     run: |
+  #       make type
+  #   - name: lint
+  #     run: |
+  #       make lint
+  #   - name: build
+  #     run: |
+  #       make build
+
+  # CINTENT >> UNSUPPORTED_OS
+  # build-macos:
+
+  #   runs-on: macos-14
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       python-version: [3.9, 3.10.6]
+
+  #   steps:
+  #   - uses: actions/checkout@v4
+  #   - name: Set up Python ${{ matrix.python-version }}
+  #     uses: actions/setup-python@v2
+  #     with:
+  #       python-version: ${{ matrix.python-version }}
+  #   - name: update pip & install custom dependencies
+  #     run: |
+  #       python -m pip install --upgrade pip
+  #       brew update
+  #       brew uninstall cmake
+  #       sh scripts/shell/m2chip_install.sh
+  #       brew install labstreaminglayer/tap/lsl
+  #       make install
+  #   - name: install dependencies
+  #     run: |
+  #       make dev-install
+  #   - name: unittest
+  #     if: always()
+  #     run: |
+  #       make coverage-report
+  #       make coverage-xml
+  #   - name: type-check
+  #     run: |
+  #       make type
+  #   - name: lint
+  #     run: |
+  #       make lint
+  #   - name: build
+  #     run: |
+  #       make build
